#!/usr/bin/env python3

import os

INT_TYPES = [
    ("int8_t", "PRId8"),
    ("int16_t", "PRId16"),
    ("int32_t", "PRId32"),
    ("int64_t", "PRId64"),
    ("uint8_t", "PRIu8"),
    ("uint16_t", "PRIu16"),
    ("uint32_t", "PRIu32"),
    ("uint64_t", "PRIu64"),
    ("char", "\"c\""),
    ("size_t", "\"zu\""),
]

FLOAT_TYPES = [
    "float",
    "double",
]

BOOL_TYPES = [
    "bool",
]

FILE_TYPES = [
    "file",
]

INT_VTABLE_TEMPLATE = """\
///////// vtable for {type_name} /////////
static int8_t cmp_{type_name}(void *a, void *b) {{
    {type_name} *ta = a;
    {type_name} *tb = b;
    return *ta - *tb;
}}
static bool eq_{type_name}(void *a, void *b) {{
    {type_name} *ta = a;
    {type_name} *tb = b;
    return *ta == *tb;
}}
static void print_{type_name}(void *a) {{
    {type_name} *ta = a;
    printf("%" {format_specifier} "", *ta);
}}
dsvtable vtable_{type_name} = {{
    .cmp = cmp_{type_name},
    .eq = eq_{type_name},
    .print = print_{type_name},
}};
"""

FLOAT_VTABLE_TEMPLATE = """\
///////// vtable for {type_name} /////////
static int8_t cmp_{type_name}(void *a, void *b) {{
    {type_name} *ta = a;
    {type_name} *tb = b;
    if (*ta < *tb) {{
        return -1;
    }} else if (*ta > *tb) {{
        return 1;
    }} else {{ // *ta == *tb
        return 0;
    }}
}}
static bool eq_{type_name}(void *a, void *b) {{
    {type_name} *ta = a;
    {type_name} *tb = b;
    return *ta == *tb;
}}
static void print_{type_name}(void *a) {{
    {type_name} *ta = a;
    printf("%g", *ta);
}}
dsvtable vtable_{type_name} = {{
    .cmp = cmp_{type_name},
    .eq = eq_{type_name},
    .print = print_{type_name},
}};
"""

BOOL_VTABLE_TEMPLATE = """\
///////// vtable for {type_name} /////////
static bool eq_{type_name}(void *a, void *b) {{
    {type_name} *ta = a;
    {type_name} *tb = b;
    return *ta == *tb;
}}
static void print_{type_name}(void *a) {{
    {type_name} *ta = a;
    printf("%s", *ta ? "true" : "false");
}}
dsvtable vtable_{type_name} = {{
    .eq = eq_{type_name},
    .print = print_{type_name},
}};
"""

FILE_VTABLE_TEMPLATE = """\
///////// vtable for {type_name} /////////
/// vtable for an array of `FILE *` values
static void drop_{type_name}(void *a) {{
    FILE **ta = a;
    fclose(*ta);
}}
dsvtable vtable_{type_name} = {{
    .drop = drop_{type_name},
}};
"""

EXTERN_VTABLE_DECL = "extern dsvtable vtable_{type_name};"

STD_VTABLES_TEMPLATE = """\
#pragma once

//////////// AUTOGENERATED FILE - DO NOT EDIT MANUALLY ////////////
//
// Generated by: codegen/vtables.py
"""

VTABLES_C_TEMPLATE = """\
//////////// AUTOGENERATED FILE - DO NOT EDIT MANUALLY ////////////
//
// Generated by: codegen/vtables.py

#include "dsvtable.h"

#include <stdio.h> // FILE, fclose
#include <inttypes.h> // PRId*, PRIu*
"""

def main():
    project_dir = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
    std_vtables_path = os.path.join(project_dir, "include", "std_dsvtables.h")
    vtables_c_path = os.path.join(project_dir, "src", "dsvtable.c")

    std_vtables_file = open(std_vtables_path, "w")
    print(STD_VTABLES_TEMPLATE, file=std_vtables_file)

    vtables_c_file = open(vtables_c_path, "w")
    print(VTABLES_C_TEMPLATE, file=vtables_c_file)

    for type_name, format_specifier in INT_TYPES:
        print(EXTERN_VTABLE_DECL.format(type_name=type_name), file=std_vtables_file)
        print(INT_VTABLE_TEMPLATE.format(
            type_name=type_name,
            format_specifier=format_specifier,
        ), file=vtables_c_file)

    for type_name in FLOAT_TYPES:
        print(EXTERN_VTABLE_DECL.format(type_name=type_name), file=std_vtables_file)
        print(FLOAT_VTABLE_TEMPLATE.format(
            type_name=type_name,
        ), file=vtables_c_file)

    for type_name in BOOL_TYPES:
        print(EXTERN_VTABLE_DECL.format(type_name=type_name), file=std_vtables_file)
        print(BOOL_VTABLE_TEMPLATE.format(
            type_name=type_name,
        ), file=vtables_c_file)

    for type_name in FILE_TYPES:
        print(EXTERN_VTABLE_DECL.format(type_name=type_name), file=std_vtables_file)
        print(FILE_VTABLE_TEMPLATE.format(
            type_name=type_name,
        ), file=vtables_c_file)

if __name__ == "__main__":
    main()
