//////////// AUTOGENERATED FILE - DO NOT EDIT MANUALLY ////////////
//
// Generated by: codegen/vtables.py

#include "dsvtable.h"

#include <stdio.h> // FILE, fclose
#include <inttypes.h> // PRId*, PRIu*

///////// vtable for int8_t /////////
static int8_t cmp_int8_t(void *a, void *b) {
    int8_t *ta = a;
    int8_t *tb = b;
    return *ta - *tb;
}
static bool eq_int8_t(void *a, void *b) {
    int8_t *ta = a;
    int8_t *tb = b;
    return *ta == *tb;
}
static void print_int8_t(void *a) {
    int8_t *ta = a;
    printf("%" PRId8 "", *ta);
}
dsvtable vtable_int8_t = {
    .cmp = cmp_int8_t,
    .eq = eq_int8_t,
    .print = print_int8_t,
};

///////// vtable for int16_t /////////
static int8_t cmp_int16_t(void *a, void *b) {
    int16_t *ta = a;
    int16_t *tb = b;
    return *ta - *tb;
}
static bool eq_int16_t(void *a, void *b) {
    int16_t *ta = a;
    int16_t *tb = b;
    return *ta == *tb;
}
static void print_int16_t(void *a) {
    int16_t *ta = a;
    printf("%" PRId16 "", *ta);
}
dsvtable vtable_int16_t = {
    .cmp = cmp_int16_t,
    .eq = eq_int16_t,
    .print = print_int16_t,
};

///////// vtable for int32_t /////////
static int8_t cmp_int32_t(void *a, void *b) {
    int32_t *ta = a;
    int32_t *tb = b;
    return *ta - *tb;
}
static bool eq_int32_t(void *a, void *b) {
    int32_t *ta = a;
    int32_t *tb = b;
    return *ta == *tb;
}
static void print_int32_t(void *a) {
    int32_t *ta = a;
    printf("%" PRId32 "", *ta);
}
dsvtable vtable_int32_t = {
    .cmp = cmp_int32_t,
    .eq = eq_int32_t,
    .print = print_int32_t,
};

///////// vtable for int64_t /////////
static int8_t cmp_int64_t(void *a, void *b) {
    int64_t *ta = a;
    int64_t *tb = b;
    return *ta - *tb;
}
static bool eq_int64_t(void *a, void *b) {
    int64_t *ta = a;
    int64_t *tb = b;
    return *ta == *tb;
}
static void print_int64_t(void *a) {
    int64_t *ta = a;
    printf("%" PRId64 "", *ta);
}
dsvtable vtable_int64_t = {
    .cmp = cmp_int64_t,
    .eq = eq_int64_t,
    .print = print_int64_t,
};

///////// vtable for uint8_t /////////
static int8_t cmp_uint8_t(void *a, void *b) {
    uint8_t *ta = a;
    uint8_t *tb = b;
    return *ta - *tb;
}
static bool eq_uint8_t(void *a, void *b) {
    uint8_t *ta = a;
    uint8_t *tb = b;
    return *ta == *tb;
}
static void print_uint8_t(void *a) {
    uint8_t *ta = a;
    printf("%" PRIu8 "", *ta);
}
dsvtable vtable_uint8_t = {
    .cmp = cmp_uint8_t,
    .eq = eq_uint8_t,
    .print = print_uint8_t,
};

///////// vtable for uint16_t /////////
static int8_t cmp_uint16_t(void *a, void *b) {
    uint16_t *ta = a;
    uint16_t *tb = b;
    return *ta - *tb;
}
static bool eq_uint16_t(void *a, void *b) {
    uint16_t *ta = a;
    uint16_t *tb = b;
    return *ta == *tb;
}
static void print_uint16_t(void *a) {
    uint16_t *ta = a;
    printf("%" PRIu16 "", *ta);
}
dsvtable vtable_uint16_t = {
    .cmp = cmp_uint16_t,
    .eq = eq_uint16_t,
    .print = print_uint16_t,
};

///////// vtable for uint32_t /////////
static int8_t cmp_uint32_t(void *a, void *b) {
    uint32_t *ta = a;
    uint32_t *tb = b;
    return *ta - *tb;
}
static bool eq_uint32_t(void *a, void *b) {
    uint32_t *ta = a;
    uint32_t *tb = b;
    return *ta == *tb;
}
static void print_uint32_t(void *a) {
    uint32_t *ta = a;
    printf("%" PRIu32 "", *ta);
}
dsvtable vtable_uint32_t = {
    .cmp = cmp_uint32_t,
    .eq = eq_uint32_t,
    .print = print_uint32_t,
};

///////// vtable for uint64_t /////////
static int8_t cmp_uint64_t(void *a, void *b) {
    uint64_t *ta = a;
    uint64_t *tb = b;
    return *ta - *tb;
}
static bool eq_uint64_t(void *a, void *b) {
    uint64_t *ta = a;
    uint64_t *tb = b;
    return *ta == *tb;
}
static void print_uint64_t(void *a) {
    uint64_t *ta = a;
    printf("%" PRIu64 "", *ta);
}
dsvtable vtable_uint64_t = {
    .cmp = cmp_uint64_t,
    .eq = eq_uint64_t,
    .print = print_uint64_t,
};

///////// vtable for char /////////
static int8_t cmp_char(void *a, void *b) {
    char *ta = a;
    char *tb = b;
    return *ta - *tb;
}
static bool eq_char(void *a, void *b) {
    char *ta = a;
    char *tb = b;
    return *ta == *tb;
}
static void print_char(void *a) {
    char *ta = a;
    printf("%" "c" "", *ta);
}
dsvtable vtable_char = {
    .cmp = cmp_char,
    .eq = eq_char,
    .print = print_char,
};

///////// vtable for size_t /////////
static int8_t cmp_size_t(void *a, void *b) {
    size_t *ta = a;
    size_t *tb = b;
    return *ta - *tb;
}
static bool eq_size_t(void *a, void *b) {
    size_t *ta = a;
    size_t *tb = b;
    return *ta == *tb;
}
static void print_size_t(void *a) {
    size_t *ta = a;
    printf("%" "zu" "", *ta);
}
dsvtable vtable_size_t = {
    .cmp = cmp_size_t,
    .eq = eq_size_t,
    .print = print_size_t,
};

///////// vtable for float /////////
static int8_t cmp_float(void *a, void *b) {
    float *ta = a;
    float *tb = b;
    if (*ta < *tb) {
        return -1;
    } else if (*ta > *tb) {
        return 1;
    } else { // *ta == *tb
        return 0;
    }
}
static bool eq_float(void *a, void *b) {
    float *ta = a;
    float *tb = b;
    return *ta == *tb;
}
static void print_float(void *a) {
    float *ta = a;
    printf("%g", *ta);
}
dsvtable vtable_float = {
    .cmp = cmp_float,
    .eq = eq_float,
    .print = print_float,
};

///////// vtable for double /////////
static int8_t cmp_double(void *a, void *b) {
    double *ta = a;
    double *tb = b;
    if (*ta < *tb) {
        return -1;
    } else if (*ta > *tb) {
        return 1;
    } else { // *ta == *tb
        return 0;
    }
}
static bool eq_double(void *a, void *b) {
    double *ta = a;
    double *tb = b;
    return *ta == *tb;
}
static void print_double(void *a) {
    double *ta = a;
    printf("%g", *ta);
}
dsvtable vtable_double = {
    .cmp = cmp_double,
    .eq = eq_double,
    .print = print_double,
};

///////// vtable for bool /////////
static bool eq_bool(void *a, void *b) {
    bool *ta = a;
    bool *tb = b;
    return *ta == *tb;
}
static void print_bool(void *a) {
    bool *ta = a;
    printf("%s", *ta ? "true" : "false");
}
dsvtable vtable_bool = {
    .eq = eq_bool,
    .print = print_bool,
};

///////// vtable for file /////////
/// vtable for an array of `FILE *` values
static void drop_file(void *a) {
    FILE **ta = a;
    fclose(*ta);
}
dsvtable vtable_file = {
    .drop = drop_file,
};

