on:
  push:
  pull_request:
    branches:
      - master

name: CI

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 1

      - name: build
        run: make

      - name: install valgrind
        run: |
          sudo apt update
          sudo apt install -y valgrind

      - name: test
        run: make test
